{
	"version": 1588707608,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/back-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/player-sheet0.png",
		"images/enem1-sheet0.png",
		"images/bosspoint-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/boss-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sept-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/chair-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/death-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/trigger-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite10-sheet1.png",
		"images/generator-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/wall-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite12-sheet1.png",
		"images/sprite12-sheet2.png",
		"media/boss.m4a",
		"media/boss.ogg",
		"media/bossdeath.m4a",
		"media/bossdeath.ogg",
		"media/death.m4a",
		"media/death.ogg",
		"media/footsteps.m4a",
		"media/footsteps.ogg",
		"media/gold.m4a",
		"media/gold.ogg",
		"media/shoot.m4a",
		"media/shoot.ogg",
		"media/shoot2.m4a",
		"media/shoot2.ogg",
		"media/03 stage 1 .m4a",
		"media/03 stage 1 .ogg",
		"media/01 title .m4a",
		"media/01 title .ogg",
		"media/04 stage clear .m4a",
		"media/04 stage clear .ogg",
		"media/06 base boss .m4a",
		"media/06 base boss .ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}